basePath: /api/v1
definitions:
  model.Center:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        example: Bangkok Center
        type: string
      updatedAt:
        type: string
    type: object
  model.CreateUserRequest:
    properties:
      agentId:
        example: "12337"
        type: string
      centerId:
        example: b94eee08-8324-4d4f-b166-d82775553a7e
        type: string
      email:
        example: Janet@exam.com
        type: string
      isActive:
        example: true
        type: boolean
      operatorId:
        example: "1233"
        type: string
      roleId:
        example: 538cd6c5-4cb3-4463-b7d5-ac6645815476
        type: string
      team:
        example: Inbound
        type: string
      userName:
        example: Janet Adebayo
        type: string
    type: object
  model.CreateUserResponse:
    properties:
      data:
        properties:
          id:
            type: string
        type: object
    type: object
  model.DeleteUserResponse:
    properties:
      message:
        example: User deleted successfully
        type: string
    type: object
  model.MessageResponse:
    properties:
      message:
        type: string
    type: object
  model.Role:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      name:
        example: Admin
        type: string
      updatedAt:
        type: string
    type: object
  model.User:
    properties:
      center:
        $ref: '#/definitions/model.Center'
      centerID:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        example: user@example.com
        type: string
      id:
        type: string
      isActive:
        type: boolean
      name:
        example: John Doe
        type: string
      role:
        $ref: '#/definitions/model.Role'
      roleID:
        type: string
      team:
        example: CEN123456
        type: string
      updatedAt:
        type: string
      userName:
        example: john.doe
        type: string
    type: object
  model.UserFilter:
    properties:
      center:
        type: string
      centerID:
        type: string
      isActive:
        type: boolean
      name:
        type: string
      role:
        type: string
      roleID:
        type: string
      sort:
        type: string
      team:
        type: string
      teamID:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: sye@aeon.co.th
    name: SYE
    url: https://aeon.co.th
  description: This is a sample server for managing cases.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Case Management API
  version: "1.0"
paths:
  /users:
    get:
      consumes:
      - application/json
      description: Retrieve all users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.User'
            type: array
      summary: Get all users
      tags:
      - Users
    post:
      consumes:
      - application/json
      description: Create a new user with the provided JSON body
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.CreateUserResponse'
      summary: Create a new user
      tags:
      - Users
  /users/{id}:
    delete:
      description: Delete a user by its ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.DeleteUserResponse'
      summary: Delete user by ID
      tags:
      - Users
    get:
      consumes:
      - application/json
      description: Retrieve user information by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
      summary: Get user by ID
      tags:
      - Users
    put:
      consumes:
      - application/json
      description: Update user information by its ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: User update payload
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.UserFilter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MessageResponse'
      summary: Update user by ID
      tags:
      - Users
  /users/import:
    post:
      consumes:
      - multipart/form-data
      description: Import user data from a CSV file asynchronously and track progress
        via task ID
      parameters:
      - description: CSV file to upload
        in: formData
        name: file
        required: true
        type: file
      - description: Optional task ID to track import progress
        in: query
        name: taskID
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/model.MessageResponse'
      summary: Import users from CSV file
      tags:
      - Users
swagger: "2.0"
